AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'node_modules/**/*'
    - 'Gemfile'
  NewCops: enable

# Customize rules
Layout/LineLength:
  Max: 100
  Exclude:
    - bin/**/*
    - config/**/*
    - test/**/*

Lint/ConstantDefinitionInBlock:
  Exclude:
    - test/**/*

Lint/DuplicateBranch:
  Enabled: false

Metrics/AbcSize:
  Max: 30
  Exclude:
    - test/**/*
    - lib/tasks/**/*

Metrics/BlockLength:
  Max: 30
  Exclude:
    - test/**/*
    - lib/tasks/**/*

Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
  Exclude:
    - test/**/*

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
  Exclude:
    - test/**/*
    - lib/tasks/location.rake

Style/Documentation:
  Exclude:
    - test/**/*

Style/FormatStringToken:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false
